language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - ./vendor/bin/phpunit --verbose
  - ./vendor/bin/php-cs-fixer fix  --dry-run --verbose
