language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - ILLUMINATE_VERSION=5.0.* TESTBENCH_VERSION=3.0.* PHPUNIT_VERSION=^4.0 EXCLUDED_TEST_GROUP=new_versions
  - ILLUMINATE_VERSION=5.1.* TESTBENCH_VERSION=3.1.* PHPUNIT_VERSION=^5.0 EXCLUDED_TEST_GROUP=new_versions
  - ILLUMINATE_VERSION=5.2.* TESTBENCH_VERSION=3.2.* PHPUNIT_VERSION=^5.0 EXCLUDED_TEST_GROUP=new_versions
  - ILLUMINATE_VERSION=5.3.* TESTBENCH_VERSION=3.3.* PHPUNIT_VERSION=^5.0 EXCLUDED_TEST_GROUP=new_versions
  - ILLUMINATE_VERSION=5.4.* TESTBENCH_VERSION=3.4.* PHPUNIT_VERSION=^5.0 EXCLUDED_TEST_GROUP=new_versions
  - ILLUMINATE_VERSION=5.5.* TESTBENCH_VERSION=3.5.* PHPUNIT_VERSION=^6.0 EXCLUDED_TEST_GROUP=none
  - ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=3.6.* PHPUNIT_VERSION=^7.0 EXCLUDED_TEST_GROUP=none
  - ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=3.7.* PHPUNIT_VERSION=^7.0 EXCLUDED_TEST_GROUP=none

matrix:
  exclude:
    # Laravel 5.6 & 5.7 do not support PHP7.0
    - php: 7.0
      env: ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=3.6.* PHPUNIT_VERSION=^7.0
    - php: 7.0
      env: ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=3.7.* PHPUNIT_VERSION=^7.0
    # Laravel 5.0 does not support PHP7.1 or higher
    - php: 7.1
      env: ILLUMINATE_VERSION=5.0.* TESTBENCH_VERSION=3.0.* PHPUNIT_VERSION=^4.0
    - php: 7.2
      env: ILLUMINATE_VERSION=5.0.* TESTBENCH_VERSION=3.0.* PHPUNIT_VERSION=^4.0
    - php: 7.3
      env: ILLUMINATE_VERSION=5.0.* TESTBENCH_VERSION=3.0.* PHPUNIT_VERSION=^4.0

before_install:
  - composer require illuminate/support:${ILLUMINATE_VERSION} illuminate/validation:${ILLUMINATE_VERSION} --no-update
  - composer require orchestra/testbench:${TESTBENCH_VERSION} --no-update
  - composer require phpunit/phpunit:${PHPUNIT_VERSION} --no-update

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover --exclude=${EXCLUDED_TEST_GROUP} --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  slack: $SLACK_CHANNEL
